// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0HYcq11TyhZk2UqivbzGQ7OaJi6hivu0',
    appId: '1:217989058560:web:e1c59b71dfbdf2b76808e5',
    messagingSenderId: '217989058560',
    projectId: 'chatlo-4c18f',
    authDomain: 'chatlo-4c18f.firebaseapp.com',
    storageBucket: 'chatlo-4c18f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp1vPtrFj8L_gqaUUwjDP6nxDsFnfc8Bc',
    appId: '1:217989058560:android:92805ec481d342ed6808e5',
    messagingSenderId: '217989058560',
    projectId: 'chatlo-4c18f',
    storageBucket: 'chatlo-4c18f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtPIwD_TtFJcCrbY1WqnMO4cer60ML4sY',
    appId: '1:217989058560:ios:78329b729c9012df6808e5',
    messagingSenderId: '217989058560',
    projectId: 'chatlo-4c18f',
    storageBucket: 'chatlo-4c18f.firebasestorage.app',
    iosBundleId: 'com.example.chatlo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtPIwD_TtFJcCrbY1WqnMO4cer60ML4sY',
    appId: '1:217989058560:ios:78329b729c9012df6808e5',
    messagingSenderId: '217989058560',
    projectId: 'chatlo-4c18f',
    storageBucket: 'chatlo-4c18f.firebasestorage.app',
    iosBundleId: 'com.example.chatlo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0HYcq11TyhZk2UqivbzGQ7OaJi6hivu0',
    appId: '1:217989058560:web:25d2da13d8824ce16808e5',
    messagingSenderId: '217989058560',
    projectId: 'chatlo-4c18f',
    authDomain: 'chatlo-4c18f.firebaseapp.com',
    storageBucket: 'chatlo-4c18f.firebasestorage.app',
  );
}

// What happens if the 